[package]
name = "trmrs_core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "trmrs_core"
path = "src/lib.rs"

[dependencies]
minipng = "1.0.0"
anyhow = "1.0.100"
log = "0.4"
